version: '3'

services:
  orchestrator:
    build:
      context: .
      target: orchestrator
    ports:
      - "8080:8080"
    environment:
      - TIME_ADDITION=1000
      - TIME_SUBTRACTION=1000
      - TIME_MULTIPLICATION=2000
      - TIME_DIVISION=2000

  agent:
    build:
      context: .
      target: agent
    depends_on:
      - orchestrator
    environment:
      - COMPUTING_POWER=10
      - ORCHESTRATOR_URL=http://localhost:8080
    deploy:
      replicas: 1